version: '3'
services:
  my-nest-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: npm run dev
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres_base
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: